### ISSUE TITLE
App funktioniert auf Android nicht mehr

### ISSUE THREAD

**Issue by heidelberger1** [muffix/couleurbummel#109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Happening on the latest app version?

- [X] I have seen this on the latest version of the app

### This is not a data update request

- [X] I am not requesting a data update

### Explain what you did

Bei Start wird "Integritätsprüfung fehlgeschlagen" angezeigt.

### Describe the bug

Ich und mehrere bekannte können die App auf Android nicht mehr nutzen (Android 14).  Die App kann gar nicht genutzt werden und die Karte ist völlig leer.

### Expected behaviour

Normaler App-Start

### Steps to reproduce

```Markdown
App starten
```

### Your device and OS

Android 14

**Comment by Plitkam** [comment]
I get this message:
"App integrity check failed
The device's or app's integrity couldn't be verified. It might not work as expected.
Please make sure to install it from the official store."

**Comment by muffix** [comment]
Thanks. Looks like Google is now requiring me to target at least API level 34 (Android 14). I'll need to bump [this](https://github.com/muffix/couleurbummel/blob/05e555c2433810ba2bfed6096e679dea022f6115/android/build.gradle#L8) and release a new version after making sure it works.

**Comment by muffix** [comment]
@heidelberger1 @Plitkam 

I've got a PR ready which upgrades the React Native version and with it the Android target SDK and the Firebase version. This should address the issues reported here. First tests are looking promising. I'll keep the version in internal testing for another day or two to make sure I haven't broken anything.

**Comment by Plitkam** [comment]
It works perfectly again, thank you for the update :)
